### ISSUE TITLE
Question about Yolo4 weights

### ISSUE THREAD

**Issue by riojano0** [Rimuto/AutoMangaCleaner#1]
Hi, Thanks for your work!

Question related to the Yolo4.weights the ones from the repo are not the same from http://auto-manga-cleaner.ru/ no? Because I try with the following image and in the web is clean correctly, but the version from the repository still keeps texts

Image source

![553ce012ce271224a9a97129e67aecce](https://user-images.githubusercontent.com/13397332/179419361-e7b89873-df52-4b72-
ab43-497291a87ec6.jpg)

Image output from repository

On the web is clean correctly
![553ce012ce271224a9a97129e67aecce](https://user-images.githubusercontent.com/13397332/179419431-23573d07-438b-44c2-a3de-c6ebbcd1e250.jpg)

**Comment by Rimuto** [comment]
Hi!
You right, weights in repo differ from web version. That's happened due to git lfs limits. You can get actual weights here - https://drive.google.com/drive/folders/1-Ali16MS27AQoR0lEec5Z-x8lAAle0K0?usp=sharing

Thank you for your interest
